# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: "CI: Build with Maven and upload Artifact"
      run: mvn -B package --file pom_prod.xml
    - run: rm target/starlink-1.jar #Remove default jar
    - run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging
    - name: Upload as release
      uses: svenstaro/upload-release-action@v2
      with:
        release_name: "Executable JAR v${{ github.run_number }}"
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: staging/csit314_starlink.jar
        tag: "v${{ github.run_number }}"
        body: "Automatically uploaded by Continuous Deployment. Changes: ${{ github.event.head_commit.message }}"
